
import { Country, CountryStatus } from './types';

export const COUNTRIES: Country[] = [
  // Prohibited
  { name: 'Afghanistan', status: CountryStatus.PROHIBITED },
  { name: 'Bahamas', status: CountryStatus.PROHIBITED },
  { name: 'Belarus', status: CountryStatus.PROHIBITED },
  { name: 'Botswana', status: CountryStatus.PROHIBITED },
  { name: 'Central African Republic', status: CountryStatus.PROHIBITED },
  { name: 'Cuba', status: CountryStatus.PROHIBITED },
  { name: 'Ghana', status: CountryStatus.PROHIBITED },
  { name: 'Guinea', status: CountryStatus.PROHIBITED },
  { name: 'Guinea-Bissau', status: CountryStatus.PROHIBITED },
  { name: 'Guyana', status: CountryStatus.PROHIBITED },
  { name: 'Iran', status: CountryStatus.PROHIBITED },
  { name: 'Iraq', status: CountryStatus.PROHIBITED },
  { name: 'North Korea', status: CountryStatus.PROHIBITED },
  { name: 'Laos', status: CountryStatus.PROHIBITED },
  { name: 'Lebanon', status: CountryStatus.PROHIBITED },
  { name: 'Libya', status: CountryStatus.PROHIBITED },
  { name: 'Myanmar', status: CountryStatus.PROHIBITED },
  { name: 'Palestinian Territories', status: CountryStatus.PROHIBITED },
  { name: 'Russia', status: CountryStatus.PROHIBITED },
  { name: 'Somalia', status: CountryStatus.PROHIBITED },
  { name: 'South Sudan', status: CountryStatus.PROHIBITED },
  { name: 'Sudan', status: CountryStatus.PROHIBITED },
  { name: 'Syria', status: CountryStatus.PROHIBITED },
  { name: 'Trinidad and Tobago', status: CountryStatus.PROHIBITED },
  { name: 'Uganda', status: CountryStatus.PROHIBITED },
  { name: 'Vanuatu', status: CountryStatus.PROHIBITED },
  { name: 'Yemen', status: CountryStatus.PROHIBITED },
  { name: 'Zimbabwe', status: CountryStatus.PROHIBITED },
  // Registration Unavailable
  { name: 'Andorra', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Aruba', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Bahrain', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Brunei', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Burkina Faso', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Burundi', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Cameroon', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Chad', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'China', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Congo - Brazzaville', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Congo - Kinshasa', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Costa Rica', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Djibouti', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Egypt', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'El Salvador', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Eritrea', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Gabon', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Gambia', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Jamaica', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Kenya', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Kuwait', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Macao SAR China', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Mali', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Mauritania', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Mauritius', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Monaco', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Namibia', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Niger', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Nigeria', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Panama', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Qatar', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Seychelles', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'South Africa', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Suriname', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Tanzania', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Turkmenistan', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Uruguay', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  { name: 'Venezuela', status: CountryStatus.REGISTRATION_UNAVAILABLE },
  // Enhanced Monitoring
  { name: 'Algeria', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'American Samoa', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Angola', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Anguilla', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Antigua & Barbuda', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Argentina', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Armenia', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Australia', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Azerbaijan', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Bangladesh', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Barbados', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Belize', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Benin', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Bermuda', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Bhutan', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Bolivia', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Bosnia & Herzegovina', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Brazil', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'British Virgin Islands', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Bulgaria', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Cape Verde', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Colombia', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Cook Islands', status: CountryStatus.ENHANCED_MONITORING },
  { name: "Côte d’Ivoire", status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Croatia', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Curaçao', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Dominica', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Ecuador', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Equatorial Guinea', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Eswatini', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Ethiopia', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Fiji', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Gibraltar', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Grenada', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Guam', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Guatemala', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Guernsey', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Haiti', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Honduras', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Hong Kong SAR China', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'India', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Isle of Man', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Israel', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Jersey', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Kazakhstan', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Kiribati', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Kyrgyzstan', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Lesotho', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Liberia', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Madagascar', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Malawi', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Maldives', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Marshall Islands', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Micronesia', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Moldova', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Mongolia', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Montenegro', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Montserrat', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Morocco', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Mozambique', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Nauru', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Nepal', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'New Zealand', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Nicaragua', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Niue', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'North Macedonia', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Pakistan', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Palau', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Papua New Guinea', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Paraguay', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Philippines', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Puerto Rico', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Rwanda', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Samoa', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Senegal', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Serbia', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Sierra Leone', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Sint Maarten', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Solomon Islands', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Sri Lanka', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'St. Helena', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'St. Kitts & Nevis', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'St. Lucia', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'St. Pierre & Miquelon', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'St. Vincent & Grenadines', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Tajikistan', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Togo', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Tonga', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Turkey', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Turks & Caicos Islands', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Tuvalu', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Ukraine', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'United Arab Emirates', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'United Kingdom', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'United States', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'U.S. Virgin Islands', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Uzbekistan', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Vatican City', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Vietnam', status: CountryStatus.ENHANCED_MONITORING },
  { name: 'Zambia', status: CountryStatus.ENHANCED_MONITORING },
  // Normal
  { name: 'Albania', status: CountryStatus.NORMAL },
  { name: 'Austria', status: CountryStatus.NORMAL },
  { name: 'Belgium', status: CountryStatus.NORMAL },
  { name: 'Canada', status: CountryStatus.NORMAL },
  { name: 'Cyprus', status: CountryStatus.NORMAL },
  { name: 'Czechia', status: CountryStatus.NORMAL },
  { name: 'Denmark', status: CountryStatus.NORMAL },
  { name: 'Dominican Republic', status: CountryStatus.NORMAL },
  { name: 'Estonia', status: CountryStatus.NORMAL },
  { name: 'Finland', status: CountryStatus.NORMAL },
  { name: 'France', status: CountryStatus.NORMAL },
  { name: 'Georgia', status: CountryStatus.NORMAL },
  { name: 'Germany', status: CountryStatus.NORMAL },
  { name: 'Greece', status: CountryStatus.NORMAL },
  { name: 'Hungary', status: CountryStatus.NORMAL },
  { name: 'Iceland', status: CountryStatus.NORMAL },
  { name: 'Indonesia', status: CountryStatus.NORMAL },
  { name: 'Ireland', status: CountryStatus.NORMAL },
  { name: 'Italy', status: CountryStatus.NORMAL },
  { name: 'Japan', status: CountryStatus.NORMAL },
  { name: 'Jordan', status: CountryStatus.NORMAL },
  { name: 'Kosovo', status: CountryStatus.NORMAL },
  { name: 'Latvia', status: CountryStatus.NORMAL },
  { name: 'Liechtenstein', status: CountryStatus.NORMAL },
  { name: 'Lithuania', status: CountryStatus.NORMAL },
  { name: 'Luxembourg', status: CountryStatus.NORMAL },
  { name: 'Malaysia', status: CountryStatus.NORMAL },
  { name: 'Malta', status: CountryStatus.NORMAL },
  { name: 'Mexico', status: CountryStatus.NORMAL },
  { name: 'Netherlands', status: CountryStatus.NORMAL },
  { name: 'Norway', status: CountryStatus.NORMAL },
  { name: 'Oman', status: CountryStatus.NORMAL },
  { name: 'Peru', status: CountryStatus.NORMAL },
  { name: 'Poland', status: CountryStatus.NORMAL },
  { name: 'Portugal', status: CountryStatus.NORMAL },
  { name: 'Romania', status: CountryStatus.NORMAL },
  { name: 'San Marino', status: CountryStatus.NORMAL },
  { name: 'Saudi Arabia', status: CountryStatus.NORMAL },
  { name: 'Singapore', status: CountryStatus.NORMAL },
  { name: 'Slovakia', status: CountryStatus.NORMAL },
  { name: 'Slovenia', status: CountryStatus.NORMAL },
  { name: 'South Korea', status: CountryStatus.NORMAL },
  { name: 'Spain', status: CountryStatus.NORMAL },
  { name: 'Sweden', status: CountryStatus.NORMAL },
  { name: 'Switzerland', status: CountryStatus.NORMAL },
  { name: 'Taiwan', status: CountryStatus.NORMAL },
  { name: 'Thailand', status: CountryStatus.NORMAL },
  { name: 'Tunisia', status: CountryStatus.NORMAL },
].sort((a, b) => a.name.localeCompare(b.name));


export const CURRENCIES = [
  'ALL',
  'AUD',
  'BGN',
  'CAD',
  'CHF',
  'CNY',
  'CZK',
  'DKK',
  'DZD',
  'EGP',
  'EUR',
  'GBP',
  'GEL',
  'HKD',
  'INR',
  'JPY',
  'MAD',
  'MXN',
  'NOK',
  'PLN',
  'RON',
  'SEK',
  'SGD',
  'TRY',
  'USD',
];
